version: '3.9'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app 
    env_file:
      - ./backend/.env-backend
    environment:
      - DJANGO_SETTINGS_MODULE=backend_to_do.settings
    depends_on:
      - postgres 

  frontend:
    container_name: frontend
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - "3000:3000" 
    volumes:     
      - ./frontend:/app      
    environment:
      - NODE_ENV=development 

  postgres:
    container_name: postgres
    image: postgres:15 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes:
  postgresdata: 